kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${artifactId}
spec:
  selector:
    matchLabels:
      app: lbl-${artifactId}
  replicas: 1
  template: 
    metadata:
      labels:
        app: lbl-${artifactId}
    spec:
      containers:
      - name: cont-${artifactId}
        image: ${artifactId}:${version}
        env:
        - name: group.id
          value: cool-consumer
        - name: bootstrap.servers
          value: kafka:9092
        - name: TOPIC
          value: mytopic
